const HOME_NAV_INFO = "HOME_NAV_INFO";
const HOME_BANNER_INFO = "HOME_BANNER_INFO"
const HOME_SPECIALS_INFO = "HOME_SPECIALS_INFO"
const REMOVE_SPECIALS = "REMOVE_SPECIALS"
export {HOME_NAV_INFO,HOME_BANNER_INFO,HOME_SPECIALS_INFO,REMOVE_SPECIALS}